query Me {
	me {
		id
		email
		firstName
		lastName
		location
		avatar
		isValid
		role
		cityRole {
			id
			label
		}
	}
}

query MyAccount {
	me {
		id
		email
		firstName
		lastName
		location
		avatar
		isValid
		role
		cityRole {
			label
			city {
				name
			}
		}
		reviews {
			POI {
				name
				slug
			}
			date
			comment
			note
			id
		}
	}
}

mutation Register($data: UserCreateInput!) {
	register(data: $data) {
		message
		success
	}
}

query Login($data: UserLoginInput!) {
	login(data: $data) {
		success
		message
	}
}

query Logout {
	logout {
		success
		message
	}
}
