query GetCategories {
	getCategories {
		id
		name
		icon
	}
}

query SearchCategories($text: String!) {
	searchCategories(text: $text) {
		id
		name
		icon
	}
}

mutation CreateCategory($data: CategoryCreateInput!) {
	createCategory(data: $data) {
		id
		name
		icon
	}
}

mutation UpdateCategory($data: CategoryUpdateInput!) {
	updateCategory(data: $data) {
		id
		name
		icon
	}
}

mutation DeleteCategory($deleteCategoryId: String!) {
	deleteCategory(id: $deleteCategoryId)
}
