query GetPOIs {
	getPOIs {
		id
		name
		description
		photos
		slug
		averageNote
		coordinates {
			x
			y
		}
		address
		budget
		city {
			id
			name
		}
		categories {
			id
			icon
			name
		}
	}
}

query GetPOIsBySlug($slug: [String!]!) {
	getPOIsBySlug(slug: $slug) {
		name
		photos
		slug
		budget
		city {
			id
			name
		}
		categories {
			icon
		}
		averageNote
	}
}

query GetPOIsBySlugDiscover($slug: [String!]!) {
	getPOIsBySlug(slug: $slug) {
		id
		name
		description
		photos
		slug
		budget
		city {
			id
			name
		}
		categories {
			icon
			name
		}
		address
		averageNote
	}
}

query GetPOIsBySlugDiscoverEdit($slug: [String!]!) {
	getPOIsBySlug(slug: $slug) {
		id
		name
		description
		photos
		slug
		averageNote
		coordinates {
			x
			y
		}
		address
		budget
		city {
			id
			name
		}
		categories {
			id
			icon
			name
		}
	}
}

query GetNearPOIs($slug: String!) {
	getNearPOIs(slug: $slug) {
		id
		name
		photos
		slug
		budget
		city {
			id
			name
		}
		categories {
			icon
			name
		}
		averageNote
	}
}

query GetPOIsByCitySlug($citySlug: String!) {
	getPOIsByCitySlug(citySlug: $citySlug) {
		id
		name
		description
		photos
		slug
		averageNote
		coordinates {
			x
			y
		}
		address
		budget
		city {
			id
			name
			slug
		}
		categories {
			id
			icon
			name
		}
	}
}

query SearchPOIs($data: SearchPOIS!) {
	searchPOIs(data: $data) {
		id
		name
		description
		photos
		slug
		averageNote
		coordinates {
			x
			y
		}
		address
		budget
		city {
			id
			name
			slug
		}
		categories {
			id
			icon
			name
		}
	}
}

mutation CreatePOI($data: POICreateInput!) {
	createPOI(data: $data) {
		id
		name
		description
		address
		slug
		photos
		coordinates {
			x
			y
		}
		city {
			id
			name
		}
		categories {
			id
			icon
			name
		}
		budget
	}
}

mutation UpdatePOI($data: POIUpdateInput!) {
	updatePOI(data: $data) {
		id
		name
		description
		photos
		slug
		coordinates {
			x
			y
		}
		address
		budget
		city {
			id
			name
		}
		categories {
			id
			icon
			name
		}
	}
}

mutation DeletePOI($deletePoiId: String!) {
	deletePOI(id: $deletePoiId)
}
