mutation CreatePOI($data: POICreateInput!) {
	createPOI(data: $data) {
		id
		name
		description
		address
		slug
		photos
		coordinates {
			x
			y
		}
		city {
			id
			name
		}
		categories {
			id
			icon
			name
		}
		budget
	}
}
