query GetReviewsByPOISlug($slug: String!) {
	getReviewsByPOISlug(slug: $slug) {
		id
		note
		comment
		date
		nbReviewsPerUser
		user {
			firstName
			avatar
		}
	}
}

mutation AddReview($data: ReviewCreateInput!) {
	addReview(data: $data) {
		id
	}
}
