query GetReviewsByPOISlug($slug: String!) {
	getReviewsByPOISlug(slug: $slug) {
		id
		note
		comment
		date
		nbReviewsPerUser
		user {
			firstName
			avatar
		}
	}
}

query GetAllReviews {
	getAllReviews {
		id
		note
		comment
		date
		user {
			email
		}
		POI {
			name
		}
	}
}

mutation AddReview($data: ReviewCreateInput!) {
	addReview(data: $data) {
		id
	}
}

mutation DeleteReview($deleteReviewId: String!) {
	deleteReview(id: $deleteReviewId) {
		success
		message
	}
}
