query GetLastUsers($limit: Float) {
	getUsers(limit: $limit) {
		id
		email
		firstName
		lastName
		location
		avatar
		isValid
		role
	}
}

query GetUsers {
	getUsers {
		id
		email
		firstName
		lastName
		location
		avatar
		isValid
		role
		cityRole {
			city {
				name
				id
			}
			label
			id
		}
	}
}

query checkPassword($data: UserLoginInput!) {
	checkPassword(data: $data)
}

mutation UpdateUser($data: UserUpdateInput!) {
	updateUser(data: $data) {
		id
		email
		firstName
		lastName
		location
		avatar
		isValid
		role
		cityRole {
			id
			label
			city {
				id
				name
			}
		}
	}
}

mutation EditUser($data: UserEditInput!) {
	editUser(data: $data) {
		id
		email
		firstName
		lastName
		location
		avatar
		isValid
		role
		cityRole {
			label
			city {
				name
				slug
			}
		}
		reviews {
			id
			note
			comment
			date
			user {
				firstName
				avatar
			}
			POI {
				name
				slug
			}
		}
	}
}

mutation DeleteUser($deleteUserId: String!) {
	deleteUser(id: $deleteUserId) {
		success
		message
	}
}

mutation EditPassword($password: String!) {
	editPassword(password: $password)
}

mutation SelfDelete {
	selfDelete
}
