services:
  db:
    image: postgis/postgis:16-3.4
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --d urbaneo -U admin" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - urbaneoDB:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
      - ./.env
    ports:
      - 4000:4000
    volumes:
      - ./backend/src/:/backend/src/
    environment:
      WDS_SOCKET_PORT: 4005
      WDS_SOCKET_HOST: 127.0.0.1
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://backend:4000/?query=%7B__typename%7D -H 'Apollo-Require-Preflight: true' || exit 1" ]
      interval: 10s
      timeout: 30s
      retries: 5
  images:
    build: ./images
    env_file:
      - ./.env
    ports:
      - 4005:4005
    volumes:
      - ./images/src:/images/src
      - urbaneoImages:/images/img
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://images:4005/hello || exit 1" ]
      interval: 10s
      timeout: 30s
      retries: 5
  frontend:
    build: ./frontend/Dockerfile.prod
    env_file:
      - ./frontend/.env
    ports:
      - 3005:3000
    volumes:
      - ./frontend/src/:/frontend/src/
      - ./frontend/public/:/frontend/public/
    depends_on:
      backend:
        condition: service_healthy
volumes:
  urbaneoDB:
  urbaneoImages:
